Repository BC-Engine-Team/BC-Engine, pull requests merged in 2022-02, with the labels that each got.

#37 Feat(BCE-41): View Different Types of Reports
  client/package-lock.json
  client/package.json
  client/src/locales/en/translation.json
  client/src/locales/fr/translation.json
  client/src/pages/Reports.js
  client/src/styles/reportsPage.css
  server/controllers/report.controller.js
  server/data_access_layer/daos/report.dao.js
  server/data_access_layer/databases.js
  server/data_access_layer/models/localdb/localdb.model.js
  server/routes/report.routes.js
  server/services/report.service.js
  server/tests/DAL/chart_report.dao.test.js
  server/tests/DAL/report.dao.test.js
  server/tests/DAL/user.dao.test.js
  server/tests/controllers/report.controller.test.js
  server/tests/services/report.service.test.js
Labels: enhancement, BC-Engine, feature

#43 Feat(BCE-11): Chart Client Type Criteria
  client/src/locales/en/translation.json
  client/src/locales/fr/translation.json
  client/src/pages/Dashboard.js
  server/controllers/invoice.controller.js
  server/data_access_layer/daos/client_grading.dao.js
  server/data_access_layer/daos/country.dao.js
  server/data_access_layer/daos/emp.dao.js
  server/data_access_layer/daos/invoice_affect.dao.js
  server/data_access_layer/daos/name.dao.js
  server/data_access_layer/daos/name_quality.dao.js
  server/data_access_layer/daos/transac.dao.js
  server/data_access_layer/daos/transac_stat.dao.js
  server/data_access_layer/daos/user.dao.js
  server/data_access_layer/databases.js
  server/data_access_layer/models/localdb/localdb.model.js
  server/data_access_layer/models/mssql_bosco/accounting_client.model.js
  server/data_access_layer/models/mssql_bosco/accounting_client_stat.model.js
  server/data_access_layer/models/mssql_pat/invoice_affect.model.js
  server/services/invoice.service.js
  server/tests/DAL/client_grading.dao.test.js
  server/tests/DAL/country.dao.test.js
  server/tests/DAL/emp.dao.test.js
  server/tests/DAL/invoice_affect.dao.test.js
  server/tests/DAL/name.dao.test.js
  server/tests/DAL/name_quality.dao.test.js
  server/tests/DAL/transac_stat.dao.test.js
  server/tests/controllers/report.controller.test.js
  server/tests/services/invoice.service.test.js
Labels: BC-Engine, feature

#49 Feat(BCE-12): Chart Account Type Criteria
  client/src/locales/en/translation.json
  client/src/locales/fr/translation.json
  client/src/pages/Dashboard.js
  server/controllers/invoice.controller.js
  server/controllers/report.controller.js
  server/data_access_layer/daos/invoice_affect.dao.js
  server/data_access_layer/daos/transac_stat.dao.js
  server/services/invoice.service.js
  server/tests/DAL/invoice_affect.dao.test.js
  server/tests/DAL/transac_stat.dao.test.js
  server/tests/controllers/report.controller.test.js
  server/tests/services/invoice.service.test.js
Labels: BC-Engine, feature

#50 Feat(BCE-211): Add Chart Report Data
  client/src/pages/Reports.js
  server/data_access_layer/databases.js
Labels: enhancement, BC-Engine, database

#51 Refactor(BCE-213): Refactor UI
  client/src/components/NavB.js
  client/src/pages/Dashboard.js
  client/src/styles/dashboardPage.css
  client/src/styles/reportsPage.css
Labels: refactoring, BC-Engine

#53 Refactor(BCE-214): Add Responsiveness To Manage Page
  client/src/Images/english.png
  client/src/Images/french.png
  client/src/components/NavB.js
  client/src/locales/en/translation.json
  client/src/locales/fr/translation.json
  client/src/pages/Dashboard.js
  client/src/pages/Manage.js
  client/src/styles/index.css
  client/src/styles/managePage.css
Labels: enhancement, refactoring, BC-Engine, localisation

#54 Feat(BCE-27): View Clients by Grading
  client/src/Images/english.png
  client/src/Images/french.png
  client/src/components/NavB.js
  client/src/locales/en/translation.json
  client/src/locales/fr/translation.json
  client/src/pages/Dashboard.js
  client/src/pages/Manage.js
  client/src/styles/index.css
  client/src/styles/managePage.css
  server/app.js
  server/controllers/manage.controller.js
  server/controllers/report.controller.js
  server/data_access_layer/daos/invoice_affect.dao.js
  server/routes/invoice.routes.js
  server/routes/manage.routes.js
  server/services/manage.service.js
  server/tests/DAL/invoice_affect.dao.test.js
  server/tests/controllers/manage.controller.test.js
  server/tests/services/manage.service.test.js
Labels: enhancement, BC-Engine, feature
